server:
  port: 8082
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/projects?currentSchema=product
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      command:
        topic: product-command-topic
    services:
      order:
        command:
          topic: order-command-topic